version: 1.0.{build}
image: Visual Studio 2022
configuration: Debug
platform: Any CPU
environment:
  _SkipNearestTargetFrameworkResolution: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test_script:
- cmd: >-
    cd IPAddressRange.Test

    dotnet test

    cd ..\IPAddressRange.Test\bin\Debug\net45

    vstest.console /logger:Appveyor IPAddressRange.Test.dll
