name: tests

on:
  push:
    branches:
      - '*'
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
           dotnet-version: '9.0.x'

      # Perform unit tests
      - name: Perform unit tests
        run: dotnet test IPAddressRange.Test -l "console;verbosity=normal" -v:q --nologo

